### ISSUE TITLE
My gemini bot didnt respond

### ISSUE THREAD

**Issue by Bmgpt** [winniesi/tg-gemini-bot#1]
Hi, I have followed all of the steps on Vercel including enter all the required variables. But why my bot still didnt respond anything once I enter /start. Please help.

**Comment by fogflea** [comment]
First clone this library to the local computer, and modify the 31 lines of tg-gemini-bot/api/telegarm.py
Replace
`self.user_name = update["message"]["from"]["username"]`
with
`self.user_name = update.get("message", {}).get("from", {}).get("username")`
Then resubmit

**Comment by fogflea** [comment]
First clone the library to the local computer, and modify the 31 lines of tg-gemini-bot/api/telegarm.py
Replace
`self.user_name = update["message"]["from"]["username"]`
with
`self.user_name = update.get("message", {}).get("from", {}).get("username")`
Then resubmit

**Comment by winniesi** [comment]
> Hi, I have followed all of the steps on Vercel including enter all the required variables. But why my bot still didnt respond anything once I enter /start. Please help.

Have you followed the [process](https://github.com/winniesi/tg-gemini-bot#get-started)
`4. Fill in your telegram bot token on the page to link telegram bot and vercel.`
 to set up the association between your telegram bot and vercel server?

Or open your vercel, check the project, open the log and copy the error message here please.

**Comment by winniesi** [comment]
> First clone the library to the local computer, and modify the 31 lines of tg-gemini-bot/api/telegarm.py Replace `self.user_name = update["message"]["from"]["username"]` with `self.user_name = update.get("message", {}).get("from", {}).get("username")` Then resubmit

I don't think that's why. I wrote it this way so if an update doesn't fit the right format, it'll quickly toss up an error. If the update's formatted like we expect, then both your code and mine should work just fine.

**Comment by winniesi** [comment]
No further description of issue

**Comment by winniesi** [comment]
This should be fixed now! ✅

The issues were:
1. **Vercel SSO Protection** was blocking webhook requests (now disabled)
2. **Webhook URL mismatch** — the Flask route is `/` but webhook was set to `/webhook`
3. **Model `gemini-flash-latest`** was resolving to an unstable preview model with ~15s latency (now using `gemini-2.5-flash`)

Redeploy the latest `main` branch and re-set your webhook to point to the root `/` path. Should work now!
