### ISSUE TITLE
Expand the access to internet

### ISSUE THREAD

**Issue by chenweiask** [winniesi/tg-gemini-bot#6]
The current Gemini model is the same as GPT3.5 which does not have internet access.
But there it could be fed with search result from internet, by which method somehow gets the ability for internet access.

Do you have any plan to expand to the function in your Gemin tg-bot?

**Comment by winniesi** [comment]
I think I can give a try, but I don't understand how to feed the content of the Internet to Gemini. Can you speak in detail?

**Comment by winniesi** [comment]
> > I think I can give a try, but I don't understand how to feed the content of the Internet to Gemini. Can you speak in detail?
> 
> First, ask ai whether this text needs to be searched online.  If not, reply "0", if necessary, reply with the keywords to be searched.
> Then, search for keywords, send the query content, search content, and search results to the AI, and then let it choose which link to enter to obtain detailed content, or directly generate a reply to the user. 

This is kind of over my head. I just want to keep it simple.🍺 @chenweiask

**Comment by chenweiask** [comment]
Thanks for the reply! The program is already very good and I respect your decision. Let's close the topic.
